# Generated by Django 4.1 on 2022-08-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('preview', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
